### ISSUE TITLE
Image for "Use of Data Policies.."

### ISSUE THREAD

**Issue by Jitka73** [cs4rl/guide#34]
https://undraw.co/search - "Terms" image 

![undraw_Terms_re_6ak4](https://user-images.githubusercontent.com/91188017/134320233-5e451e36-da3b-434a-9b5a-957ef91cf67e.png)

For the small picture on page 16

**Comment by Jitka73** [comment]
Sorry, I thought I added it to the image list. I am completely new on Github.

**Comment by Jitka73** [comment]
file:///C:/Users/jstha/Downloads/undraw_data_processing_yrrv.svg This pictogram could be used on page 17 for Data standards. Found in https://undraw.co/search - "data processing" 

Maybe it gets too boring with the same style on two alternating pages, but could pep it up by modifying colours - this is done in undraw.

**Comment by mrchristian** [comment]
images used
